### ISSUE TITLE
command "project" not found

### ISSUE THREAD

**Issue by ramdandi** [alexcasalboni/serverless-starter-python#3]
I am getting error while trying to follow your instructions.

  Serverless Error ---------------------------------------

```
 command "project" not found, Run "serverless help" for
 a list of all available commands.
```

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

serverless help

Commands
- Serverless documentation: http://docs.serverless.com
- You can run commands with "serverless" or the shortcut "sls"
- Pass "--help" after any <command> for contextual help

create ................... Create new Serverless Service.
deploy ................... Deploy Service.
deploy function .......... Deploys a single function from the service
info ..................... Displays information about the service.
invoke ................... Invokes a deployed function.
logs ..................... Outputs the logs of a deployed function.
remove ................... Remove resources.
tracking ................. Enable or disable usage tracking.

Plugins
AwsCompileApigEvents, AwsCompileFunctions, AwsCompileS3Events, AwsCompileSNSEvents, AwsCompileScheduledEvents, AwsDeploy, AwsDeployFunction, AwsInfo, AwsInvoke, AwsLogs, AwsRemove, Create, Deploy, Info, Invoke, Logs, Package, Remove, Tracking

**Comment by jonkyops** [comment]
Did this on windows, so commands may be slightly different. Try running this:
`serverless install --url https://github.com/alexcasalboni/serverless-starter-python`

**Comment by alexcasalboni** [comment]
Sorry guys, the repo hasn't been updated since version 0.5 of the Framework. I promise I'll update code & instructions asap! :)

**Comment by alexcasalboni** [comment]
Update: [this](https://github.com/bennybauer/serverless-python-sample) is the new official Python plugin (powered by [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) too!).

I'm going to deprecate this repo.
